project:
  type: website
  preview:
    port: 4200
    browser: true

website:
  title: "Arjun Srivastava"
  site-url: https://www.arjunsriva.com
  navbar:
    right:
      - about.qmd
      - text: Library
        href: https://arjunsriva.com/library
      - text: Podcast
        href: /podcast
      - text: TIL
        href: /til
      - icon: twitter
        href: https://twitter.com/arjunsriv
      # - icon: github
      #   href: https://github.com/arjunbazinga
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/arjunsriva
      - icon: rss
        href: index.xml
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  google-analytics: "UA-101184475-1"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-overflow: wrap