---
title: Experimentation Platforms
description: An Overview of Experimentation Platforms.
layout: post
categories: [Experimentation]
comments: false


date: "2021-03-21"
---

## Books

- [Trustworthy Online Controlled Experiments](https://www.arjunsriva.com/library/book_1/book_1183.html)

## Resources

- [Top Challenges from the first Practical Online Controlled Experiments Summit](https://research.fb.com/wp-content/uploads/2019/06/Top-Challenges-from-the-first-Practical-Online-Controlled-Experiments-Summit.pdf)

- [A/B Testing Pitfalls: Getting Numbers You Can Trust is Hard](https://www.youtube.com/watch?v=HEGI5QN3fXE)

- [USF Business Analytics Forum - Ron Kohavi](https://www.youtube.com/watch?v=wT3dBSVGgjA)

- [A/B Testing at Scale: Accelerating Software Innovation ](http://videolectures.net/kdd2017_tutorial15_software_innovation/)

- [Trustworthy Online Controlled Experiments at Large Scale ](https://www.youtube.com/watch?v=kTAFOCynWIg)

- [Always Valid Inference: Continuous Monitoring of A/B Tests](https://www.youtube.com/watch?v=BanBrr3Hzm8)

## Companies

#### Netflix

- [Netflix Articles tagged Experimentation](https://netflixtechblog.com/tagged/experimentation)
- [It’s All A/Bout Testing: The Netflix Experimentation Platform](https://netflixtechblog.com/its-all-a-bout-testing-the-netflix-experimentation-platform-4e1ca458c15)
- [Reimagining Experimentation Analysis at Netflix](https://netflixtechblog.com/reimagining-experimentation-analysis-at-netflix-71356393af21)
- [Success stories from a democratized experimentation platform](https://drive.google.com/file/d/1TjTkgSzGQXtFxro5vdInUUIpsmJPdCiO/view)
- [Key Challenges with Quasi Experiments at Netflix](https://netflixtechblog.com/key-challenges-with-quasi-experiments-at-netflix-89b4f234b852)
- [Data Compression for Large-Scale Streaming Experimentation](https://netflixtechblog.com/data-compression-for-large-scale-streaming-experimentation-c20bfab8b9ce)
- [Page Simulation for Better Offline Metrics at Netflix](https://netflixtechblog.com/page-simulator-fa02069fb269)

- [Streaming Video Experimentation at Netflix: Visualizing Practical and Statistical Significance](https://netflixtechblog.com/streaming-video-experimentation-at-netflix-visualizing-practical-and-statistical-significance-7117420f4e9a)
- [Innovating Faster on Personalization Algorithms at Netflix Using Interleaving](https://netflixtechblog.com/interleaving-in-online-experiments-at-netflix-a04ee392ec55)

#### Microsoft

- [ExP Experimentation Platform Accelerating software innovation through trustworthy experimentation](https://exp-platform.com/)
- [Online Experimentation at Microsoft](https://ai.stanford.edu/~ronnyk/ExPThinkWeek2009Public.pdf)
- [Experimentation Platform](https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/)
- [A/B Testing and Covid-19: Data-Driven Decisions in Times of Uncertainty](https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/articles/a-b-testing-and-covid-19-data-driven-decisions-in-times-of-uncertainty/)
- [Patterns of Trustworthy Experimentation: Pre-Experiment Stage](https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/articles/patterns-of-trustworthy-experimentation-pre-experiment-stage/)

#### Twitter

- [Twitter experimentation: technical overview](https://blog.twitter.com/engineering/en_us/a/2015/twitter-experimentation-technical-overview.html)

#### Google

- [Overlapping Experiment Infrastructure: More, Better, Faster Experimentation](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/36500.pdf)

#### Facebook

- [PlanOut is a library and interpreter for designing online experiments.](http://facebook.github.io/planout/)
- [Adaptive Experimentation Platform](https://github.com/facebook/Ax)

#### Spotify

- [Spotify’s New Experimentation Platform part 1](https://engineering.atspotify.com/2020/10/29/spotifys-new-experimentation-platform-part-1/)
- [Spotify’s New Experimentation Platform part 2](https://engineering.atspotify.com/2020/11/02/spotifys-new-experimentation-platform-part-2/)
- [Large Scale Experimentation at Spotify](https://www.infoq.com/news/2016/12/large-experimentation-spotify/)

#### Tinder

- [Phoenix — Tinder’s Testing Platform, Part — I](https://medium.com/tinder-engineering/phoenix-tinders-testing-platform-part-i-8e51c19ca977)
- [Phoenix — Tinder’s Testing Platform — Part II](https://medium.com/tinder-engineering/phoenix-tinders-testing-platform-part-ii-e99fbc72af55)
- [Phoenix — Tinder’s Testing Platform — Part III](https://medium.com/tinder-engineering/phoenix-tinders-testing-platform-part-iii-520728b9537)

#### LinkedIn

- [Our evolution towards T-REX: The prehistory of experimentation infrastructure at LinkedIn](https://engineering.linkedin.com/blog/2020/our-evolution-towards-t-rex--the-prehistory-of-experimentation-i)
- [Making the LinkedIn experimentation engine 20x faster](https://engineering.linkedin.com/blog/2020/making-the-linkedin-experimentation-engine-20x-faster)

#### Uber

- [Under the Hood of Uber's Experimentation Platform](https://eng.uber.com/xp/)
- [A/B testing at Uber: How we built a BYOM (bring your own metrics) platform](https://conferences.oreilly.com/strata/strata-ny-2018/public/schedule/detail/69126.html)
- [Building an Intelligent Experimentation Platform with Uber Engineering](https://eng.uber.com/experimentation-platform/)

#### AirBnB

- [4 Principles for Making Experimentation Count](https://medium.com/airbnb-engineering/4-principles-for-making-experimentation-count-7a5f1a5268a)
- [Scaling Airbnb’s Experimentation Platform](https://medium.com/airbnb-engineering/https-medium-com-jonathan-parks-scaling-erf-23fd17c91166)
- [Experiment Reporting Framework](https://medium.com/airbnb-engineering/experiment-reporting-framework-4e3fcd29e6c0#.cbl72jip2)

#### Instagram

- [Lessons Learned at Instagram Stories and Feed Machine Learning](https://instagram-engineering.com/lessons-learned-at-instagram-stories-and-feed-machine-learning-54f3aaa09e56)

#### Go-Jek

- [Introducing Litmus: GOJEK's Own Experimentation Platform](https://blog.gojekengineering.com/introducing-litmus-gojeks-own-experimentation-platform-3803467b6a53)

#### InstaCart

- [Randomized, controlled experiments and multivariate regression are used to continuously improve the grocery delivery engine ](https://tech.instacart.com/it-all-depends-4bb7b22e854b)

#### Pintrest

- [Building Pinterest’s A/B testing platform](https://medium.com/pinterest-engineering/building-pinterests-a-b-testing-platform-ab4934ace9f4)

## Conferences

- [Experimentation Culture Awards](https://experimentationcultureawards.com/#register)

## SASS solutions

- [Split.io](https://www.split.io/)
- [Optimizely](https://www.optimizely.com/)

## When you can't run A/B Tests

- [Quasi Experimentation at Netflix](https://netflixtechblog.com/quasi-experimentation-at-netflix-566b57d2e362)
- [Key Challenges with Quasi Experiments at Netflix](https://netflixtechblog.com/key-challenges-with-quasi-experiments-at-netflix-89b4f234b852)
- [Mostly Harmless Econometrics: An Empiricist's Companion](https://www.arjunsriva.com/library/book_1/book_1176.html)

## Notes

### [2020 CODE@MIT Experimentation platforms](https://youtu.be/8yLC5oBP9fI)

- Gaussian processes
- Multi touch attributions
- Heterogenous treatment effect
- Interaction effects
- Overlapping experiments
- What are potential over evaluation criteria ?
- What are good guardrail metrics ?
- run A/A tests.

Canary Deploys by using Experimentation platform to tell when you break guard rail metrics
